<?php

use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Carbon\Carbon;
use Illuminate\Support\Facades\Artisan;

class EventTest extends TestCase
{
    /**
     * A basic test example.
     *
     * @return void
     */
    use DatabaseTransactions;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Artisan::call('migrate:refresh');
        Artisan::call('db:seed');
    }

    public function test_create_event()
    {
        $data = [
            'name' => 'testCase',
            'location' => 'testCase',
            'start_time' => Carbon::parse('2000-12-31 23:59:59')->format('Y-m-d H:i:s'),
            'end_time' => Carbon::parse('2000-12-31 23:59:59')->format('Y-m-d H:i:s'),
            'category' => 'testCase',
            'description' => 'testCase',
            'owner_id' => '4'
        ];
        $response = $this->call('POST', "api/event", $data);
        $response->assertStatus(201);
    }

    public function test_get_users()
    {
        $this->json('GET', "api/event/24/members")->assertStatus(200)->decodeResponseJson();
    }

    public function test_update_event()
    {
        $data = [
            'name' => 'testCaseUpdate',
            'location' => 'testCaseUpdate',
            'start_time' => Carbon::parse('2010-12-31 00:00:00')->format('Y-m-d H:i:s'),
            'end_time' => Carbon::parse('2010-12-31 00:00:00')->format('Y-m-d H:i:s'),
            'category' => 'testCaseUpdate',
            'description' => 'testCaseUpdate',
            'owner_id' => '4'
        ];
        $response = $this->call('PUT', "api/event/24/update", $data);
        $response->assertStatus(200);
    }

    public function test_get_all_events()
    {
        $this->json('GET', "api/events/0/ASC")->assertStatus(200)->decodeResponseJson();
    }

    public function test_leave_event()
    {
        $response = $this->call('DELETE', "api/event/25/2");
        $response->assertStatus(200);
    }
}
